### PR TITLE
feat: Added Pizza Fact

### PR DESCRIPTION
**Pull request by prw760**
## Description

Added a pizza fact into the repo's fact and trivia markdown file

## What type of PR is this? (check all applicable)

- [X] ☝️ Add a pizza fact or trivia
- [ ] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [ ] 🍴 Add a traditional food
- [ ] 📝 Documentation Update

## Related Tickets & Documents

Relates to #36 

## Added to documentation?

- [ ] 📜 README.md
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by adiati98** [comment]
Hey @prw760,

You have a [failed check here](https://github.com/open-sauced/pizza-verse/pull/96#pullrequestreview-2062160970). You need to address it before we can review your PR.

Thank you! 🙂

**Comment by prw760** [comment]
Hi, Ayu.   I fixed the problem with the title of the PR, and it appears to have passed the checks now.   Hopefully this is merge ready, finally!  Thanks again.

**Comment by adiati98** [comment]
You did fix the problem, @prw760! Well done! 🎉 

But can you please change the issue number?
At the moment, you're referring to the closed PR number. 🙂 

Also, you need to put "Relates to" and not "Fixes" in front of the issue number to keep it open as mentioned in the issue.
Thanks!

**Comment by prw760** [comment]
Hi, again, Ayu.   I fixed the issue number (to #36) and also changed "Fixes" to "Relates to".   Hopefully this works! :)

**Review by adiati98 — APPROVED** [review]
Thank you, @prw760!!! 🚀

**Comment by prw760** [comment]
You are super patient, Ayu! That's an incredible skill. Thanks again for all your help! Every time you have an issue with one of my PRs, I learn more. :)

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by adiati98** [comment]
And so are you, Paul! You have growth mindset which is very important to have. 🙌🏼

**Pull request merged**
