### PR TITLE
I have added some pizza related fun facts

### LINKED ISSUE #27: Feature: I want to add  some facts
### Type of feature

🍕 Feature

### Current behavior

I want to some facts relate pizza to the under Fun-facts and trivia 

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by kumar007ambi**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #27
## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @kumar007ambi. Thanks for your contribution! :) Can you please raise the issue about your contribution in the Issues section? It'll help the maintainers and contributors who want to review your PR gain a better understanding of it.

**Comment by kumar007ambi** [comment]
@CBID2  Okay, I will raise a issue

**Review by CBID2 — APPROVED** [review]
Well done @kumar007ambi. As you progress in your open source journey, remember the following:
1. Raise an issue and want for it be assigned to you before you submit your PR.
2. Follow the directions in the PR form to ensure that it's filled out effectively.

Also, join our [Discord](https://discord.com/invite/U2peSNf23P) if you have any more questions about open source. 
Happy Contributing! 😊

**Comment by kumar007ambi** [comment]
@CBID2 can you add hacktober fest accepted tag. By adding tag it will help in my contribution to a valid hactober fest contribution

**Pull request merged**
