### PR TITLE
Add a pizza fact

### PR DESCRIPTION
**Pull request by Kaz-Smino**
## Description
This PR adds a pizza fact.

## What type of PR is this? (check all applicable)

- [x] ☝️ Add a pizza fact or trivia
- [ ] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [ ] 📝 Documentation Update

## Related Tickets & Documents
Relates to https://github.com/open-sauced/pizza-verse/issues/36

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @Kaz-Smino. Can you fix the **Related Tickets and Documents** section of your PR form? Per the instructions, you have to put `Relates to` then the issue that your contribution addresses. It makes it easier for me and the other maintainers to review it.

**Comment by Kaz-Smino** [comment]
Hi @CBID2. I've modified it just now.

**Review by CBID2 — APPROVED** [review]
Interesting fact @Kaz-Smino! :) If you haven't already, join our [Discord community](https://discord.com/invite/U2peSNf23P) to get more updates on OpenSauced or to find other projects to contribute to.

**Review by CBID2 — CHANGES_REQUESTED** [review]
Ignore my previous comment @Kaz-Smino, can you also fill out the description section of your PR?

**Comment by Kaz-Smino** [comment]
@CBID2 Thank you for teaching me. Next time, I'll pay attention to the rule of PR.

**Review by CBID2 — APPROVED** [review]
Great job @Kaz-Smino! :) If you haven't already, join our [Discord community](https://discord.com/invite/U2peSNf23P) to get more updates on OpenSauced or to find other projects to contribute to.

**Pull request merged**
