### PR TITLE
feat: add samosa to world-traditional-food.md

### PR DESCRIPTION
**Pull request by chydeepak7**
## Description

This PR adds a food to world-traditional-food.md

## What type of PR is this? (check all applicable)

- [ ] ☝️ Add a pizza fact or trivia
- [ ] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [x] 🍴 Add a traditional food
- [ ] 📝 Documentation Update

## Related Tickets & Documents

Relates to #86 

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @chydeepak7,

Thank you for your contribution! ✨ 

Folks might want to know why Samosa is delicious. So, I have a suggestion here, that would also benefits others.

Can you add information about:

- What's the filling of Samosa?
- What's the sauce(s) that are good to dip Samosa into? 

You can google them or look it up at Wikipedia. 🙂

**Comment by adiati98** [comment]
Hi @chydeepak7,

I'm curious about this (and I believe many others, too!)

Can you add a little bit information about:

- What's the filling of Samosa?
- What's the sauce(s) that are good to dip Samosa into?

These would be a great information for folks who wants to know what this food is all about and perhaps even want to try it! ✨

**Comment by chydeepak7** [comment]
Yes, I added

**Review by adiati98 — APPROVED** [review]
Well done and thank you for letting us know more about Samosa, @chydeepak7! ✨ 

thank you GIF

**Pull request merged**
