### PR TITLE
Added New Fact about Largest Pizza Festivale 

### PR DESCRIPTION
**Pull request by MrAshwin2142**
## Description
This PR adds a new pizza fact about Largest Pizza Festivale to the list.

## What type of PR is this? (check all applicable)

- [x] ☝️ Add a pizza fact or trivia
- [ ] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [ ] 📝 Documentation Update

## Related Tickets & Documents
Relates to #36 

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

##  What GIF best describes this PR or how it makes you feel?

download

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @MrAshwin2142. Can you fill out the Related Tickets and Documents and Description sections of your PR form? Also, can you give a more descriptive title as opposed to "add a new pizza fact"? It'll add more context to your contribution.

**Comment by CBID2** [comment]
Hey @MrAshwin2142. Are you still work on this?

**Comment by CBID2** [comment]
Why did you close this PR @MrAshwin2142?

**Comment by MrAshwin2142** [comment]
sorry , but i am confused.

**Comment by CBID2** [comment]
> sorry , but i am confused.

What are you confused about @MrAshwin2142?

**Comment by CBID2** [comment]
> What specific changes do I have to make?
> 
> 

Hi @MrAshwin2142. You need to revise the sections in your PR template like I mentioned [here](https://github.com/open-sauced/pizza-verse/pull/66#issuecomment-1825067649). It'll make it easier for me to review your contribution as it provides more context.

**Review by CBID2 — APPROVED** [review]
Well done @MrAshwin2142!

**Pull request merged**
