### PR TITLE
Feature/add sisig pizza recipe

### PR DESCRIPTION
**Pull request by nickaldwin**
## Description
This PR adds a section about Sisig Pizza to the pizza-recipe.md file.

## What type of PR is this? (check all applicable)

- [ ] ☝️ Add a pizza fact or trivia
- [X] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [ ] 📝 Documentation Update

## Related Tickets & Documents
 Relates to #32 

## Added to documentation?

- [ ] 📜 README.md
- [X] 🙅 no documentation needed

## [optional] What GIF best describes this PR or how it makes you feel?
 😊

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @nickaldwin! :) Can you fill out the other sections of your Pull Request's form please? It'll make it easier for me to review your contribution. Consider using [this Pull Request as an example](https://github.com/open-sauced/pizza-verse/pull/25).

**Comment by nickaldwin** [comment]
Hi @CBID2 i update the PR form i apologize if i skip the comments thank you

**Comment by CBID2** [comment]
> Hi @CBID2 i update the PR form i apologize if i skip the comments thank you

@nickaldwin, you haven't linked the issue that your PR addresses. I highly recommend looking the example PR that I previously provided you to fill out that section.

**Comment by nickaldwin** [comment]
> > Hi @CBID2 i update the PR form i apologize if i skip the comments thank you
> 
> @nickaldwin, you haven't linked the issue that your PR addresses. It's done like this: `Relates to #issue number` [This is the issue your pull request addresses](https://github.com/open-sauced/pizza-verse/issues/36)

oh i missed that one

**Comment by nickaldwin** [comment]
Hi @CBID2, I hope this is correct this time. I have updated the pull request description with related tickets and documents. This closes #72

**Comment by CBID2** [comment]
@nickaldwin read the last paragraph in this issue: https://github.com/open-sauced/pizza-verse/issues/36
It's the one that corresponds to your PR.

**Comment by nickaldwin** [comment]
hi @CBID2 i figured it out i update the related and tickets & docs section

**Comment by CBID2** [comment]
> hi @CBID2 i figured it out i update the related and tickets & docs section

Alright, now we're getting somewhere @nickaldwin! :) Now, I can officially review your contribution

**Comment by nickaldwin** [comment]
@CBID2 thank you

**Review by CBID2 — APPROVED** [review]
Great job @nickaldwin! :) As you continue your open source journey, remember to fill out every section of your pull request’s form. It makes it easier for maintainers and other contributors to review your contribution. If you enjoyed your experience with us, share your rating on [Repo-Rater](https://repo-rater.eddiehub.io/), and join our [Discord](https://discord.com/invite/U2peSNf23P) for more updates on OpenSauced & to find other projects.

**Comment by nickaldwin** [comment]
@CBID2 I should pay attention to details in things thank you so much for your advice.

**Pull request merged**
