### PR TITLE
Replaced logo

### LINKED ISSUE #79: Chores: Replace the logo in this repo's README
> [!IMPORTANT]
> If you've worked on a good first issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

## Description

The logo in this repo's README is the old one, we should replace it with the new one.

Screenshot 2024-04-25 at 7 13 57 AM

## Suggested Solution

Replace the logo by changing the link in the `src` with the below:

https://github.com/open-sauced/assets/blob/main/logos/logo-on-dark.png

Line to be changed:

https://github.com/open-sauced/pizza-verse/blob/6a3137efa6dbfd0d91683d45e3ae814fb42ba262/README.md?plain=1#L3

### PR DESCRIPTION
**Pull request by Sandeep18JS**
## Description

This PR adds the Logo on Documentation.

## What type of PR is this? (check all applicable)

- [ ] ☝️ Add a pizza fact or trivia
- [ ] 🧑‍🍳 Add a pizza recipe
- [ ] 🗺️ Add a regional pizza
- [x] 📝 Documentation Update

## Related Tickets & Documents

Fixes #79 

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @Sandeep18JS,

Thank you for working on this! ✨

For now, I'll assign you to the issue. But next time, please read our [contributing guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/). You need to be assigned to an issue before you can work on the changes. 🙂 

Please read the issue carefully. We want you to replace the link in the `src` and not adding the logo to the asset.

Can you please:
- remove the logo from the asset
- change the link to the logo
- remove the width
- fix the `alt` with "OpenSauced"

You can refer to this line of code on our app repo.

https://github.com/open-sauced/app/blob/1da1c519222093b8fd9f9abbddffda4c3094fce2/README.md?plain=1#L3

Please let me know if you have any question. Thanks!

**Comment by adiati98** [comment]
@Sandeep18JS I'm not sure why I can't assign or tag you in the issue. So, I'll leave a comment there.

**Review by adiati98 — APPROVED** [review]
Thanks, @Sandeep18JS! 🙌

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊

git merge GIF

**Comment by adiati98** [comment]
Hey @Sandeep18JS,

Is there any reason why you close this PR after it's approved?

This PR hasn't been merged yet. It still need one more approval from our team before it can be merged.

If you don't want to proceed, I will unassign you from the issue and give it to someone else. Just let me know. Thanks.

**Comment by Sandeep18JS** [comment]
@Sandeep18JS sorry my mistake , yea you can unassign me for now.

**Pull request closed without merging**
