### PR TITLE
docs: adding Old Forge Pizza to update regional-pizza.md

### PR DESCRIPTION
**Pull request by Emmarie-Ahtunan**
## Description

This PR adds the feature of Old Forge Style Pizza to regional-pizza.md 

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

This relates to #35

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @Emmarie-Ahtunan. Are you still working on this?

**Comment by Emmarie-Ahtunan** [comment]
Hi @CBID2 Yes, I just got a phone call from a friend who lives out of state. I'll finish it very soon.

**Comment by CBID2** [comment]
> Hi @CBID2 Yes, I got a phone call from a friend who lives out of state. I'll finish it very soon, in a couple of hours. If that's okay.

Ohh take your time @Emmarie-Ahtunan. I just wanted to see if things are fine :)

**Comment by Emmarie-Ahtunan** [comment]
I started a new one to clean up the files. Apologies for being on the phone so long with my friend today. Thanks for checking in @CBID2

**Pull request closed without merging**
