### PR TITLE
Added remaining pizza recipes to the table of contents

### PR DESCRIPTION
**Pull request by kumar007ambi**
## Description
I have added remaining pizza recipes to the table of contents.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [☑ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

#41 this is the issue number 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by kumar007ambi** [comment]
@CBID2 I have fix the issue and do not forget to add the hactoberfest tag😀.

**Review by CBID2 — APPROVED** [review]
Merge time

**Comment by CBID2** [comment]
> @CBID2 I think you have forgotten about the tag, please add the hactoberfest tag😅

Done :)

**Comment by BekahHW** [comment]
@kumar007ambi you only need the hacktoberfest tag if the repo isn't labeled hacktoberfest.

**Comment by BekahHW** [comment]
@kumar007ambi I'm saying that it's not necessary for us to add it to each PR bc we're using the label on the whole repo:

image

**Comment by kumar007ambi** [comment]
@BekahHW Okay I understood your point 😀

**Comment by kumar007ambi** [comment]
@BekahHW I was worried that if the tag is not present in my PR then my contribution will not be counted😁.

**Pull request merged**
