### PR TITLE
Create Savory_Pear_and_Gorgonzola_Pizza_with_Balsamic_Glaze.md

### PR DESCRIPTION
**Pull request by DevJSter**
Experience a culinary symphony of flavors with our Savory Pear and Gorgonzola Pizza. This gourmet creation transcends the traditional pizza concept, beckoning you to embark on a sensory journey where the sweet, savory, and tangy notes choreograph a dance across your taste buds. 

**Description**

This Pull Request adds a delectable pizza recipe to our repository. The Savory Pear and Gorgonzola Pizza is a testament to the art of blending unexpected yet complementary flavors. Ripe pears, with their natural sweetness, elegantly intertwine with the richness of Gorgonzola cheese, creating a harmonious contrast. What elevates this pizza to a culinary masterpiece is the finishing touch of a balsamic glaze drizzle, adding a nuanced layer of sophistication and comfort to every slice.

**Type of PR**

- [x] 🧑‍🍳 Add a pizza recipe

**Related Tickets & Documents**

Related to #32

**Added to documentation?**

- [x] 📜 README.md

**Optional GIF**

image

**Additional Notes**
- Please savor this recipe and share your feedback.
- This pizza is a perfect blend of sophistication and comfort, making it a delightful addition to any pizza lover's repertoire. Enjoy the culinary journey!

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @DevJSter! :) Can you add this entry to the [`recipe.md` file](https://github.com/open-sauced/pizza-verse/blob/main/pizza-recipes.md)

**Comment by DevJSter** [comment]
Hii @CBID2!! I;ve added this entry to the `pizza-reciepe.md` file!!

**Comment by CBID2** [comment]
> Hii @CBID2!! I;ve added this entry to the `pizza-reciepe.md` file!!

Good @DevJSter, now can you remove the `savory_Pear_and_Gorgonzola_Pizza_with_Balsamic_Glaze.md" file?

**Review by CBID2 — APPROVED** [review]
Well done @DevJSter! If you want to stay updated on OpenSauced, join our [Discord Community](https://discord.gg/opensauced)! :) We'd love to have you! 😊

**Pull request merged**
