### PR TITLE
Add new fact to pizza-facts-&-trivia.md

### PR DESCRIPTION
**Pull request by Justin-Quinn51**
## Description

Added pizza trivia

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Relates to #36 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Thanks for your Pull Request @Justin-Quinn51! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

**Comment by Justin-Quinn51** [comment]
Thanks for your help @CBID2! I've attempted to resolve the merge conflicts, in addition to adding on my pizza fact. Please let me know if anything else needs to be modified.

**Comment by CBID2** [comment]
> Thanks for your help @CBID2! I've attempted to resolve the merge conflicts, in addition to adding on my pizza fact. Please let me know if anything else needs to be modified.
> 
> 
> 
> 

Hi @Justin-Quinn51, we're now using unordered list with dash (-) instead of ordered list (number), so change your PR to that style please

**Comment by Justin-Quinn51** [comment]
@CBID2 I think I may have accidentally closed the PR while I was trying to sort out some conflicts. Is there any way to reopen this, or should I just make a new PR? Sorry for the confusion, I'm not sure why I'm having so many issues...

**Comment by BekahHW** [comment]
@Justin-Quinn51 it says that you deleted the repository, so I can't reopen the PR.

**Comment by Justin-Quinn51** [comment]
@BekahHW I decided to start fresh, sorry for all of the confusion. I appreciate the help from you and @CBID2. Thank you for your patience.

The new PR is #57 for reference.

**Pull request closed without merging**
